algoritmo "Exercício 02"
//2) Solicite um valor e apresente as mensagens: “Valor positivo”,
//“Valor negativo” ou “Zero”
// Autor : Rafael Rodrigues Oliveira Santos
// Data : 22/08/2024
var
n1: real
inicio
escreva("Informe um valor aleatório: ")
leia(n1)
escreval
  se(n1 > 0) entao
    escreval("O número", n1, " e positivo!")
  senao
    escreval("O número", n1, " e negativo!")
  fimse

fimalgoritmo
