algoritmo "Exercício 03"
//3) Solicite dois valores (supostamente distintos) e
//apresente qual é o maior valor
// Autor : Rafael Rodrigues Oliveira Santos
// Data : 22/08/2024
var
n1,n2: real
inicio
escreva("Informe um número: ")
leia(n1)
escreva("Informe um segundo número: ")
leia(n2)
escreval
se(n1 > n2) entao
  escreval("O número", n1, " é maior que", n2)
  senao
    escreval("O número", n2, " é maior que", n1)
fimse

fimalgoritmo
