algoritmo "Exercício 03"
//3) Solicite uma string qualquer e apresenta-a toda em minúsculo ao usuário
// Autor : Rafael Rodrigues Oliveira Santos
// Data : 05/09/2024
var
palavra: caracter
inicio
escreval("Tranformador de palavras para minúsculo:")

escreval("----------------------------------------------------------------------------------")

escrevaL("Informe uma palavra qualquer: ")
leia(palavra)

palavra <- minusc(palavra)

escreval("----------------------------------------------------------------------------------")

escreval("Palavra informada em minúculo: ",palavra)

escreval("----------------------------------------------------------------------------------")
fimalgoritmo
